# Generated by Django 5.2.17 on 2026-09-30 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código interno')),
                ('categoria', models.CharField(choices=[('Proyección', 'Proyección'), ('Fotografía', 'Fotografía'), ('Audio', 'Audio'), ('Otros', 'Otros')], default='Otros', max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='ubicación')),
                ('imagen', models.ImageField(blank=True, upload_to='equipos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Docente', 'Docente'), ('Estudiante', 'Estudiante')], default='Docente', max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha de uso')),
                ('bloque', models.PositiveSmallIntegerField(choices=[(1, 'Bloque 1: 08:30 - 10:00 hrs'), (2, 'Bloque 2: 10:15 - 11:45 hrs'), (3, 'Bloque 3: 12:00 - 13:30 hrs'), (4, 'Bloque 4: 14:30 - 16:00 hrs'), (5, 'Bloque 5: 16:15 - 17:45 hrs')], verbose_name='bloque horario')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'bloque'],
            },
        ),
    ]
